import logging

STORAGE_PATH = "/home/user/gogdb/"
NUM_PRODUCT_TASKS = 4
UPDATER_LOGLEVEL = logging.INFO

DEBUG = True

JINJA_LSTRIP_BLOCKS = True
JINJA_TRIM_BLOCKS = True

ASSETS_AUTO_BUILD = True
ASSETS_DEBUG = True
